import { promises as fs } from 'fs'

import { themeToCssEntries } from 'invariance'
import type { ThemeJsonV2 } from 'invariance'

// Marker pair delimiting the scanner-owned :root block inside the app's
// globals.css. Re-runs replace ONLY between these markers, so the developer's
// own CSS (including their own :root) is never touched.
export const GEN_START = '/* INVARIANCE-GENERATED:start — regenerated by invariance-scan, do not hand-edit */'
export const GEN_END = '/* INVARIANCE-GENERATED:end */'

/**
 * Render the initial theme's roles+slots as a marked :root block. Uses the
 * SAME ordered entry list (themeToCssEntries) the client apply + SSR paths
 * consume, so the static baseline can never disagree with runtime tokens.
 */
export function renderRootBlock(theme: ThemeJsonV2): string {
  const decls = themeToCssEntries(theme)
    .map(([key, value]) => `  ${key}: ${value};`)
    .join('\n')
  return `${GEN_START}\n:root {\n${decls}\n}\n${GEN_END}\n`
}

/**
 * Idempotently write the generated :root block into globals.css. If a prior
 * block exists (between the markers) it is replaced in place; otherwise the
 * block is appended. The app's own CSS is preserved verbatim.
 */
export async function patchGlobalsCss(globalsCssFile: string, theme: ThemeJsonV2): Promise<void> {
  const block = renderRootBlock(theme)
  const existing = await fs.readFile(globalsCssFile, 'utf-8')

  const startIdx = existing.indexOf(GEN_START)
  if (startIdx !== -1) {
    const endIdx = existing.indexOf(GEN_END, startIdx)
    const tail = endIdx !== -1 ? existing.slice(endIdx + GEN_END.length) : ''
    const next = existing.slice(0, startIdx) + block.replace(/\n$/, '') + tail
    await fs.writeFile(globalsCssFile, next, 'utf-8')
    return
  }

  const sep = existing.endsWith('\n') ? '\n' : '\n\n'
  await fs.writeFile(globalsCssFile, existing + sep + block, 'utf-8')
}
