import yaml from 'js-yaml'

import { parseConfig } from '../../config/parser'
import type { InvarianceConfig, ThemeJson } from '../../config/types'

const CONFIG_HEADER = `# Invariance Config — generated by invariance-scan
# All sections locked to observed values. To unlock customization:
#   npx invariance-unlock --status              # see what's locked
#   npx invariance-unlock colors                # allow any colors
#   npx invariance-unlock fonts                 # allow any fonts
#   npx invariance-unlock layout                # allow layout changes
#   npx invariance-unlock page / --level 2      # set page level
#   npx invariance-unlock all                   # unlock everything
# Or edit this file directly — the config is the source of truth.

`

export function emitConfigYaml(config: InvarianceConfig): string {
  const out = yaml.dump(config, { lineWidth: 120, quotingType: '"', noRefs: true })
  try {
    parseConfig(out)
  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err)
    throw new Error(`emitConfigYaml produced invalid config: ${msg}`)
  }
  return CONFIG_HEADER + out
}

export function emitInitialThemeJson(theme: ThemeJson): string {
  return `${JSON.stringify(theme, null, 2)}\n`
}
