import type { AppManifest } from "@invariance/schema";
import type { RepoScan } from "./scan";

/**
 * INVARIANCE.md: the wiring half of `init`. The manifest makes customization
 * *describable*; these edits make it *live* — client SDK for Tier-0 UI
 * overlays, server SDK for Tier-1 API-seam hooks. Emitted as a reviewable
 * guide rather than auto-edits: integration points (root component, server
 * entry) are the riskiest places to guess wrong in someone else's codebase.
 */
export function renderGuide(scan: RepoScan, manifest: AppManifest): string {
  const { react, next, express } = scan.frameworks;
  const appId = manifest.appId;
  const lines: string[] = [];

  lines.push(`# Wiring Invariance into ${appId}`);
  lines.push("");
  lines.push(
    `Generated by \`invariance init\`. Found: ${manifest.designTokens.length} design tokens, ` +
      `${manifest.endpoints.length} endpoints, ${manifest.components.length} components ` +
      `(${[next && "Next.js", react && !next && "React", express && "Express"]
        .filter(Boolean)
        .join(" + ") || "framework not detected"}).`,
  );
  lines.push("");
  lines.push(`Review \`invariance.manifest.json\` first — it is the contract every`);
  lines.push(`user mod is verified against. Tighten it before wiring anything:`);
  lines.push(`remove tokens/endpoints users should never touch, and add policies`);
  lines.push(`for fields that must hold (prices, roles, totals).`);
  lines.push("");

  lines.push(`## 1. Client SDK (Tier 0: UI customization)`);
  lines.push("");
  if (react || next) {
    lines.push("Wrap your root component" + (next ? " (e.g. in `app/layout.tsx`)" : "") + ":");
    lines.push("");
    lines.push("```tsx");
    lines.push(`import { InvarianceProvider, PromptWidget } from "@invariance/client/react";`);
    lines.push("");
    lines.push(`<InvarianceProvider config={{`);
    lines.push(`  registryUrl: process.env.INVARIANCE_REGISTRY ?? "http://localhost:4400",`);
    lines.push(`  appId: "${appId}",`);
    lines.push(`  subjectId: currentUser.id,  // your stable per-user id`);
    lines.push(`}}>`);
    lines.push(`  <App />`);
    lines.push(`  <PromptWidget />  {/* the end-user "customize" entry point */}`);
    lines.push(`</InvarianceProvider>`);
    lines.push("```");
  } else {
    lines.push("No React detected — use the framework-agnostic build:");
    lines.push("");
    lines.push("```html");
    lines.push(`<script type="module">`);
    lines.push(`  import { init } from "@invariance/client/vanilla";`);
    lines.push(`  init({ registryUrl: "...", appId: "${appId}", subjectId: "..." });`);
    lines.push(`</script>`);
    lines.push("```");
  }
  lines.push("");

  lines.push(`## 2. Server SDK (Tier 1: API-seam hooks)`);
  lines.push("");
  if (express) {
    lines.push("Mount the middleware before your routes:");
    lines.push("");
    lines.push("```ts");
    lines.push(`import { createInvarianceMiddleware } from "@invariance/server";`);
    lines.push("");
    lines.push(`app.use(createInvarianceMiddleware({`);
    lines.push(`  registryUrl: process.env.INVARIANCE_REGISTRY ?? "http://localhost:4400",`);
    lines.push(`  appId: "${appId}",`);
    lines.push(`  // default subject resolution: x-invariance-subject header;`);
    lines.push(`  // override with getSubject(req) to read your session instead.`);
    lines.push(`}));`);
    lines.push("```");
  } else if (next) {
    lines.push("Wrap your route handlers with the fetch-style adapter:");
    lines.push("");
    lines.push("```ts");
    lines.push(`import { withInvariance } from "@invariance/server";`);
    lines.push("");
    lines.push(`export const GET = withInvariance(`);
    lines.push(`  { registryUrl: "...", appId: "${appId}" },`);
    lines.push(`  async (req) => { /* your handler */ },`);
    lines.push(`);`);
    lines.push("```");
  } else {
    lines.push("No Express/Next detected. Tier-1 hooks need the server SDK at your");
    lines.push("API seam — see `@invariance/server` for the Express and fetch adapters.");
  }
  lines.push("");
  lines.push("Hooks only execute inside a sandbox, only against endpoints declared in");
  lines.push("the manifest, and only with capabilities a signed bundle declares. Any");
  lines.push("failure falls back to your unmodified API behavior.");
  lines.push("");

  lines.push(`## 3. Publish the manifest on every release`);
  lines.push("");
  lines.push("```sh");
  lines.push(`invariance manifest publish --file invariance.manifest.json \\`);
  lines.push(`  --registry $INVARIANCE_REGISTRY`);
  lines.push("```");
  lines.push("");
  lines.push("Publishing a new version marks affected user mods stale; they revalidate");
  lines.push("lazily on each user's next session (compatible mods migrate, broken ones");
  lines.push("degrade to base behavior with an AI re-fix offer).");
  lines.push("");

  lines.push(`## 4. Local development`);
  lines.push("");
  lines.push("```sh");
  lines.push("invariance dev   # local control plane on :4400, publishes this manifest");
  lines.push("```");
  lines.push("");

  return lines.join("\n");
}
