import { describe, expect, it } from "vitest";
import { generateSigningKeyPair } from "@invariance/schema/signing";
import { ROLE_TOKENS, THEME_PACKS, chromaOf, type StyleSpec } from "@invariance/design/server";
import { createDesignAwareAgent } from "../src/modules/authoring/design-author";
import { authorMod, refixMod } from "../src/modules/authoring/pipeline";
import { publishManifest, revalidateSubject } from "../src/modules/registry";
import { MemoryStore } from "../src/store";
import type { AuthoringAgent } from "../src/modules/authoring/agent";

// Phase 6: the deterministic re-fix payoff of storing the StyleSpec. When a
// developer ships a manifest that tightens a design constraint, a degraded
// theme mod is regenerated by RECOMPILING its stored StyleSpec under the new
// constraints — no LLM, no re-prompt.
const keys = generateSigningKeyPair();
const spec: StyleSpec = THEME_PACKS.find((p) => p.id === "retro-arcade")!.spec; // vivid accent

function manifest(version: string, policies: unknown[]) {
  return {
    appId: "app1",
    version,
    designTokens: ROLE_TOKENS.map((name) => ({ name, kind: "color", value: "#000000" })),
    components: [],
    endpoints: [],
    policies,
    createdAt: "2026-06-10T00:00:00.000Z",
  };
}

// A base agent that explodes if invoked — proves the re-fix path never touches an LLM.
const exploding: AuthoringAgent = {
  generateDraft: () => Promise.reject(new Error("LLM ran during a deterministic theme re-fix")),
};

describe("deterministic theme re-fix via recompile", () => {
  it("degrades a theme under a tightened constraint, then recompiles it — no LLM", async () => {
    const store = new MemoryStore();

    // v1: lenient. Author a theme mod (Designer stubbed to a vivid-accent spec).
    await publishManifest(store, "app1", manifest("1.0.0", [{ type: "design-constraint", id: "aa", contrast: 4.5 }]));
    const agent = createDesignAwareAgent(exploding, { classify: () => true, design: async () => spec });
    const authored = await authorMod({ store, keys, agent, appId: "app1", subjectId: "u1", prompt: "retro arcade" });
    expect(authored.ok, !authored.ok ? JSON.stringify(authored.reasons) : "").toBe(true);

    // v2: clamp the accent chroma below the vivid accent the theme shipped.
    await publishManifest(store, "app1", manifest("2.0.0", [{ type: "design-constraint", id: "chroma", accentChromaMax: 0.05 }]));

    // The standing theme is stale; on revalidation its vivid accent fails the new
    // cap, so it degrades (and the design provenance survives the rebind).
    const ptr = await revalidateSubject(store, keys, "app1", "u1");
    expect(ptr.status).toBe("degraded");

    // Re-fix: recompile the stored StyleSpec under v2 — the compiler clamps the
    // accent — yielding an active bundle, deterministically (0 attempts, no LLM).
    const fixed = await refixMod({ store, keys, agent: exploding, appId: "app1", subjectId: "u1" });
    expect(fixed.ok, !fixed.ok ? JSON.stringify(fixed.reasons) : "").toBe(true);
    if (!fixed.ok) return;
    expect(fixed.attempts).toBe(0);

    const bundle = JSON.parse(fixed.record.envelope.payload);
    const accent = (bundle.uiOps as Array<{ token: string; value: string }>).find(
      (o) => o.token === "--inv-accent",
    )!.value;
    expect(chromaOf(accent)!).toBeLessThanOrEqual(0.05 + 1e-6);
    // Provenance is preserved through the recompile.
    expect(bundle.design.styleSpec.mode).toBe(spec.mode);
  });
});
